sudo: required
services:
  - docker

python:
  - "3.6"

language: python

script:
  - python -m pytest -v

after_success:
  - sh .travis/deploy_dockerhub.sh
  - pip install requests
  - python .travis/post_rpi.py